server:
  port: 8081

spring:
  application:
    name: Corporate-Credit-Management-Platform
  data:
    mongodb:
      uri: mongodb://localhost:27017/creditPlatform
      database: creditPlatform

app:
  admin:
    password: admin123

jwt:
  secret: corporate-bank-credit-management-secret
  expiration: 86400000   # 1 day in milliseconds


